### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by jobartucz** [shanemay/MossApp#3]
Downloaded the repository and tried to run setup.exe - got the following error:

PLATFORM VERSION INFO
	Windows 			: 10.0.17134.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3056.0 built by: NET472REL1
	clr.dll 			: 4.7.3362.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3056.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17134.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/john/Downloads/MossApp-master/MossApp-master/MossApp/Publish/MossApp.application
	Application url			: file:///C:/Users/john/Downloads/MossApp-master/MossApp-master/MossApp/Publish/Application%20Files/MossApp_2_0_0_7/MossApp.exe.manifest

IDENTITIES
	Deployment Identity		: MossApp.application, Version=2.0.0.7, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\john\Downloads\MossApp-master\MossApp-master\MossApp\Publish\MossApp.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, MossApp.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [3/16/2019 3:15:39 PM] : Activation of C:\Users\john\Downloads\MossApp-master\MossApp-master\MossApp\Publish\MossApp.application has started.
	* [3/16/2019 3:15:39 PM] : Processing of deployment manifest has successfully completed.
	* [3/16/2019 3:15:39 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [3/16/2019 3:15:39 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, MossApp.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by PicchiKevin** [comment]
You should either:
- Compile everything yourself :)
- Extract the setup.zip and then execute the setup.exe

**Comment by jobartucz** [comment]
That's what I did. Extracted setup.zip and tried to run setup.exe. Got the errors above.

**Comment by PicchiKevin** [comment]
@jobartucz Did recompiling work?

**Comment by shanemay** [comment]
@jobartucz Did you get it installed or running? I downloaded the Setup zip folder and tried the install, it worked fine. Reach out to me at smay1@nwacc.edu if you have trouble and I will gladly help.

**Comment by jobartucz** [comment]
@PicchiKevin @shanemay I am out of town this week, but will try it when I get back. Thanks for the support.

**Comment by BEEugene** [comment]
Hi! 
I had the same issue, after extracting the setup again and rerunning it several times the verification successfully passed. 
How long should I wait till registration will be done?

**Comment by jc-camosun** [comment]
I [forked this repository](https://github.com/jc-camosun/MossApp) and added an AppVeyor CI file. You can d/l the built exe directly under [releases](https://github.com/jc-camosun/MossApp/releases).
